### PR TITLE
 improved the document in many ways

### PR DESCRIPTION
**Pull request by pletzer**
Hi @mkienzle, 

 * removed any mentions of dev repo
 * simplified and fixed the diagram
 * added definition of collaborator/contributor
 * tried to enforce naming consistency

### CODE REVIEW

**Review by mkienzle — APPROVED** [review]
Thanks Alex: looks good to me.

**Comment by pletzer** [comment]
Let me fix some conflicts

**Comment by mkienzle** [comment]
ok, I saw some conflict popping up with Samik's most recent pull-request: would you like me to close this pull-request or resolve or else?

**Comment by pletzer** [comment]
I resolved the conflicts... try to accept the PR

**Comment by pletzer** [comment]
It has Samik's changes in a separate section.

**Comment by SamikDatta** [comment]
Hi @pletzer - I think we need the section about Tortoisegit further up in the document (before Section 4). Basically, those using Windows and Tortoisegit will have no idea how to do the steps in Section 3, and won't be able to start working on a branch, needed before Section 4 is carried out.

**Pull request merged**
